---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: sops-akv-decryptor
  namespace: flux-system
spec:
  clientID: 7e114157-085b-4fce-81e5-e39619e32717
  resourceID: /subscriptions/d4f000ed-cd74-40bd-b261-839141802148/resourcegroups/gitops-demo-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/SopsDecryptorIdentity
  type: 0 # user-managed identity
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: sops-akv-decryptor-binding
  namespace: flux-system
spec:
  azureIdentity: sops-akv-decryptor
  selector: sops-akv-decryptor  # kustomize-controller label will match this name
